ciliumNetworkPolicy:
  enabled: true

registry:
  domain: gsoci.azurecr.io

image:
  name: "giantswarm/pss-operator"
  tag: ~

provider:
  kind: ""

pod:
  user:
    id: 1000
  group:
    id: 1000

# Pod securityContext
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Container securityContext
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

global:
  podSecurityStandards:
    enforced: true
